import { Injectable } from '@angular/core';
import { SingleProduct } from '../interfaces/single-product';

@Injectable({
  providedIn: 'root',
})
export class AccessoriesService {
  constructor() {}
  accData: SingleProduct[] = [
    {
      productTitle: 'portfel',
      type: 'skórzany',
      price: 219,
      productImage: '../../../../assets/imgs/all-prods/ac1.jpg',
      id: 1000001,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'akcesoria',
    },
    {
      productTitle: 'portfel',
      type: 'skórzany',
      price: 349,
      productImage: '../../../../assets/imgs/all-prods/ac2.jpg',
      id: 1000002,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'akcesoria',
    },
    {
      productTitle: 'portfel',
      type: 'skórzany',
      price: 788,
      productImage: '../../../../assets/imgs/all-prods/ac3.jpg',
      id: 1000003,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'akcesoria',
    },
    {
      productTitle: 'portfel',
      type: 'skórzany z rgb',
      price: 215,
      productImage: '../../../../assets/imgs/all-prods/ac4.jpg',
      id: 1000004,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'akcesoria',
    },
    {
      productTitle: 'portfel',
      type: 'skórzany',
      price: 138,
      productImage: '../../../../assets/imgs/all-prods/ac5.jpg',
      id: 1000005,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'akcesoria',
    },
    {
      productTitle: 'portfel',
      type: 'skórzany',
      price: 79,
      productImage: '../../../../assets/imgs/all-prods/ac6.jpg',
      id: 1000006,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'akcesoria',
    },
    {
      productTitle: 'portfel',
      type: 'skórzany',
      price: 223,
      productImage: '../../../../assets/imgs/all-prods/ac7.jpg',
      id: 1000007,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'akcesoria',
    },
    {
      productTitle: 'portfel',
      type: 'skórzany',
      price: 119,
      productImage: '../../../../assets/imgs/all-prods/ac8.jpg',
      id: 1000008,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'akcesoria',
    },
    {
      productTitle: 'portfel',
      type: 'skórzany',
      price: 139,
      productImage: '../../../../assets/imgs/all-prods/ac9.jpg',
      id: 1000009,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'akcesoria',
    },
    {
      productTitle: 'portfel',
      type: 'skórzany',
      price: 88,
      productImage: '../../../../assets/imgs/all-prods/ac10.jpg',
      id: 1000010,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'akcesoria',
    },
    {
      productTitle: 'portfel',
      type: 'skórzany',
      price: 189,
      productImage: '../../../../assets/imgs/all-prods/ac11.jpg',
      id: 1000011,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'akcesoria',
    },
    {
      productTitle: 'portfel',
      type: 'skórzany',
      price: 319,
      productImage: '../../../../assets/imgs/all-prods/ac12.jpg',
      id: 1000012,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'akcesoria',
    },
    {
      productTitle: 'portfel',
      type: 'skórzany',
      price: 159,
      productImage: '../../../../assets/imgs/all-prods/ac13.jpg',
      id: 1000013,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'akcesoria',
    },
  ];
}
