import { Injectable } from '@angular/core';
import { SingleProduct } from '../interfaces/single-product';

@Injectable({
  providedIn: 'root',
})
export class NecklaceService {
  constructor() {}

  neckData: SingleProduct[] = [
    {
      productTitle: 'naszyjnik',
      type: 'złoty',
      price: 179,
      productImage: '../../../../assets/imgs/all-prods/neck1.jpg',
      id: 10001,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'naszyjniki',
    },
    {
      productTitle: 'naszyjnik',
      type: 'czarne korale',
      price: 89,
      productImage: '../../../../assets/imgs/all-prods/neck2.jpg',
      id: 10002,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'naszyjniki',
    },
    {
      productTitle: 'naszyjnik',
      type: 'korale',
      price: 269,
      productImage: '../../../../assets/imgs/all-prods/neck3.jpg',
      id: 10003,
      discountValue: 0,
      discount: false,
      bestseller: true,
      path: 'naszyjniki',
    },
    {
      productTitle: 'naszyjnik',
      type: 'srebrny',
      price: 199,
      productImage: '../../../../assets/imgs/all-prods/neck4.png',
      id: 10004,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'naszyjniki',
    },
    {
      productTitle: 'naszyjnik',
      type: 'srebrny z kamieniem',
      price: 149,
      productImage: '../../../../assets/imgs/all-prods/neck5.jpg',
      id: 10005,
      discountValue: 0,
      discount: false,
      bestseller: true,
      path: 'naszyjniki',
    },
    {
      productTitle: 'naszyjnik',
      type: 'białe korale',
      price: 109,
      productImage: '../../../../assets/imgs/all-prods/neck6.jpg',
      id: 10006,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'naszyjniki',
    },
    {
      productTitle: 'naszyjnik',
      type: 'pozłacany z kamieniem',
      price: 144,
      productImage: '../../../../assets/imgs/all-prods/neck7.jpg',
      id: 10007,
      discountValue: 50,
      discount: true,
      bestseller: false,
      path: 'naszyjniki',
    },
    {
      productTitle: 'naszyjnik',
      type: 'srebrny z kamieniami',
      price: 399,
      productImage: '../../../../assets/imgs/all-prods/neck8.jpg',
      id: 10008,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'naszyjniki',
    },
    {
      productTitle: 'naszyjnik',
      type: 'srebrny',
      price: 179,
      productImage: '../../../../assets/imgs/all-prods/neck9.jpg',
      id: 10009,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'naszyjniki',
    },
    {
      productTitle: 'naszyjnik',
      type: 'srebrny',
      price: 249,
      productImage: '../../../../assets/imgs/all-prods/neck10.jpg',
      id: 10010,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'naszyjniki',
    },
    {
      productTitle: 'naszyjnik',
      type: 'srebrny w kształcie serca',
      price: 315,
      productImage: '../../../../assets/imgs/all-prods/neck11.jpg',
      id: 10011,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'naszyjniki',
    },
    {
      productTitle: 'naszyjnik',
      type: 'korale',
      price: 229,
      productImage: '../../../../assets/imgs/all-prods/neck12.jpg',
      id: 10012,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'naszyjniki',
    },
  ];
}
