import { Injectable } from '@angular/core';
import { SingleProduct } from '../interfaces/single-product';

@Injectable({
  providedIn: 'root',
})
export class RingsService {
  constructor() {}

  ringsData: SingleProduct[] = [
    {
      productTitle: 'pierścień',
      type: 'srebrny',
      price: 179,
      productImage: '../../../../assets/imgs/all-prods/ring1.jpg',
      id: 1,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'pierścionki',
    },
    {
      productTitle: 'pierścień',
      type: 'srebrny z kamieniem',
      price: 189,
      productImage: '../../../../assets/imgs/all-prods/ring2.jpg',
      id: 2,
      discountValue: 0,
      discount: false,
      bestseller: true,
      path: 'pierścionki',
    },
    {
      productTitle: 'pierścień',
      type: 'złoty',
      price: 319,
      productImage: '../../../../assets/imgs/all-prods/ring3.jpg',
      id: 3,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'pierścionki',
    },
    {
      productTitle: 'pierścień',
      type: 'złoty',
      price: 249,
      productImage: '../../../../assets/imgs/all-prods/ring4.jpg',
      id: 4,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'pierścionki',
    },
    {
      productTitle: 'pierścień',
      type: 'złoty z kamieniami',
      price: 379,
      productImage: '../../../../assets/imgs/all-prods/ring5.jpg',
      id: 5,
      discountValue: 44,
      discount: true,
      bestseller: false,
      path: 'pierścionki',
    },
    {
      productTitle: 'pierścień',
      type: 'złoty z kamieniami',
      price: 229,
      productImage: '../../../../assets/imgs/all-prods/ring6.jpg',
      id: 6,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'pierścionki',
    },
    {
      productTitle: 'pierścień zaręczynowy',
      type: 'srebrny z kamieniami',
      price: 899,
      productImage: '../../../../assets/imgs/all-prods/ring7.jpg',
      id: 7,
      discountValue: 25,
      discount: true,
      bestseller: false,
      path: 'pierścionki',
    },
    {
      productTitle: 'pierścień',
      type: 'złoty z diamentem',
      price: 1799,
      productImage: '../../../../assets/imgs/all-prods/ring8.jpg',
      id: 8,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'pierścionki',
    },
    {
      productTitle: 'pierścień',
      type: 'srebrny z kamieniem',
      price: 919,
      productImage: '../../../../assets/imgs/all-prods/ring9.jpg',
      id: 9,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'pierścionki',
    },
    {
      productTitle: 'pierścień',
      type: 'srebrny z kamieniem',
      price: 549,
      productImage: '../../../../assets/imgs/all-prods/ring10.jpg',
      id: 10,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'pierścionki',
    },
    {
      productTitle: 'pierścień',
      type: 'srebrny z kamieniami',
      price: 999,
      productImage: '../../../../assets/imgs/all-prods/ring11.jpg',
      id: 11,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'pierścionki',
    },
    {
      productTitle: 'pierścień',
      type: 'złoty z kamieniami',
      price: 379,
      productImage: '../../../../assets/imgs/all-prods/ring12.jpg',
      id: 12,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'pierścionki',
    },
    {
      productTitle: 'pierścień',
      type: 'srebrny z diamentem',
      price: 2499,
      productImage: '../../../../assets/imgs/all-prods/ring13.jpg',
      id: 13,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'pierścionki',
    },
    {
      productTitle: 'pierścień',
      type: 'złoty z diamentem',
      price: 3299,
      productImage: '../../../../assets/imgs/all-prods/ring14.jpg',
      id: 14,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'pierścionki',
    },
  ];
}
