import { Injectable } from '@angular/core';
import { SingleProduct } from '../interfaces/single-product';

@Injectable({
  providedIn: 'root',
})
export class WatchesService {
  constructor() {}

  watchesData: SingleProduct[] = [
    {
      productTitle: 'zegarek',
      type: 'dior',
      price: 1019,
      productImage: '../../../../assets/imgs/all-prods/watch1.jpg',
      id: 100001,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'zegarki',
    },
    {
      productTitle: 'zegarek',
      type: 'rolex',
      price: 12999,
      productImage: '../../../../assets/imgs/all-prods/watch2.jpg',
      id: 100002,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'zegarki',
    },
    {
      productTitle: 'zegarek',
      type: 'fossil',
      price: 6499,
      productImage: '../../../../assets/imgs/all-prods/watch3.jpg',
      id: 100003,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'zegarki',
    },
    {
      productTitle: 'zegarek',
      type: 'fossil',
      price: 5799,
      productImage: '../../../../assets/imgs/all-prods/watch4.jpg',
      id: 100004,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'zegarki',
    },
    {
      productTitle: 'zegarek',
      type: 'maserati',
      price: 8199,
      productImage: '../../../../assets/imgs/all-prods/watch5.jpg',
      id: 100005,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'zegarki',
    },
    {
      productTitle: 'zegarek',
      type: 'seiko',
      price: 4499,
      productImage: '../../../../assets/imgs/all-prods/watch6.jpg',
      id: 100006,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'zegarki',
    },
    {
      productTitle: 'zegarek',
      type: "tempo d'oro",
      price: 3300,
      productImage: '../../../../assets/imgs/all-prods/watch7.jpg',
      id: 100007,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'zegarki',
    },
    {
      productTitle: 'zegarek',
      type: 'diamond dior',
      price: 11999,
      productImage: '../../../../assets/imgs/all-prods/watch8.jpg',
      id: 100008,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'zegarki',
    },
    {
      productTitle: 'zegarek',
      type: 'rolex',
      price: 24999,
      productImage: '../../../../assets/imgs/all-prods/watch9.jpg',
      id: 100009,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'zegarki',
    },
    {
      productTitle: 'zegarek',
      type: 'rolex',
      price: 33200,
      productImage: '../../../../assets/imgs/all-prods/watch10.jpg',
      id: 100010,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'zegarki',
    },
    {
      productTitle: 'zegarek',
      type: 'qmax',
      price: 7560,
      productImage: '../../../../assets/imgs/all-prods/watch11.jpg',
      id: 100011,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'zegarki',
    },
    {
      productTitle: 'zegarek',
      type: 'fossil',
      price: 9590,
      productImage: '../../../../assets/imgs/all-prods/watch12.jpg',
      id: 100012,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'zegarki',
    },
    {
      productTitle: 'zegarek',
      type: 'casio',
      price: 3500,
      productImage: '../../../../assets/imgs/all-prods/watch13.jpg',
      id: 100013,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'zegarki',
    },
    {
      productTitle: 'zegarek',
      type: 'festina',
      price: 800,
      productImage: '../../../../assets/imgs/all-prods/watch14.jpg',
      id: 100014,
      discountValue: 0,
      discount: false,
      bestseller: false,
      path: 'zegarki',
    },
  ];
}
